### ISSUE TITLE
Organizer - Send Notification Button

### ISSUE THREAD

**Issue by ruchali1** [CMPUT301F24nachos/nachos-business#48]
Organizers will need the option to:

- [x] send notifications to chosen entrants to now sign up #25 
- [x] send notifications to all entrants on the waiting list #34 
- [x] send notifications to all selected entrants #35 
- [x] send a notification to all cancelled entrants #29 

Validation: 

- [x]  Will need to ensure that the entrants are correctly labelled with only one of; on waiting list, selected to sign up, signed up (selected), cancelled per event. #49
